Northwind.MVC/Models/ErrorViewModel.cs
namespace Northwind.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Northwind.MVC/Controllers/CardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Northwind.MVC.Controllers
{
    public class CardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Northwind.MVC/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Northwind.API.Repositories;

namespace Northwind.MVC.Controllers
{
    public class EmployeeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
    }
}

Northwind.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Northwind.MVC.Models;
using System.Diagnostics;

namespace Northwind.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Northwind.MVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace Northwind.MVC.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Northwind.MVC/Views/Card/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-9">
                <table class="table table-hover" id="cardTable">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>UnitPrice</th>
                            <th>Quantity</th>
                            <th>Sub Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="cardTableBody">
                    </tbody>
                </table>
            </div>
            <div class="col-md-3 text-center">
                <h1>Total Price</h1>
                <h2 id="totalPrice"></h2>
                <button id="complete" class="btn btn-primary">Complete Card</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="/js/card.js"></script>
}

Northwind.MVC/Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover" id="employeeTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody id="employeeBody">

            </tbody>
        </table>
    </div>
    <div class="col-md-12 d-none" id="employeeCard"> 
        <div class="card">
            <div class="card-body">
                <h1 id="employeeFullName"></h1>
                <p class="lead">Toplam <strong id="employeeTotalSaleCount"></strong> adet satış yapmıştır.</p>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="/js/employee.js"></script>
}

Northwind.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Northwind.MVC/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-hover" id="productTable">
    <thead>
        <tr>
            <th>Product Id</th>
            <th>Product Name</th>
            <th>UnitPrice</th>
            <th>Stock</th>
            <th>Category</th>
            <th>Supplier</th>
        </tr>
    </thead>
    <tbody id="productTableBody">

    </tbody>
</table>

@section Scripts{
    <script src="/js/product.js"></script>
}

Northwind.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Northwind.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Northwind.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Report">Order Reports</a>
                        </li>
                    </ul>
                    <a asp-action="Index" asp-controller="Card" class="btn btn-secondary ms-auto">
                        <p id="count"></p>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Northwind.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>